/// <summary>
///   Author(s):       Joe Zachary
///                    Jim de St. Germain - Refactor/Documentation for ASP Core
///   Course:          CS 3500
///   Date:            2011 Sept   - Initial Grid Code
///                    2020 Spring - Refactor for ASP Core
///   
///   Partial:
/// 
///     The code for this class is divided into two files using C#'s partial ability.
///     The other half is in the SpreadsheetPanel.cs file.  This code was
///     (somewhat) automatically generated by the WYSIWYG design editor.  It should not
///     be directly modified.  Personalizations should be done in the other half of the partial.
/// 
///   Contents:
///   
///     See SpreadsheetPanel.cs for more information.
/// 
/// </summary>
namespace SS
{
    partial class SpreadsheetPanel
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        }

        #endregion
    }
}